### ISSUE TITLE
Reason of :all index

### ISSUE THREAD

**Issue by soulfly** [ileitch/modis#6]
Can someone guide me what is the reason to have that **:all** index?

https://github.com/ileitch/modis/blob/master/lib/modis/persistence.rb#L201
https://github.com/ileitch/modis/blob/master/lib/modis/persistence.rb#L131

I did not find a place where it is used, but it consumes our server's RAM

**Comment by Tonkpils** [comment]
It's actually used for the `all` finder method. https://github.com/ileitch/modis/blob/master/lib/modis/finder.rb#L17

**Comment by Tonkpils** [comment]
If you have any other issues with this feel free to re-open
